### ISSUE TITLE
feature request: accept path str in load and dump methods

### ISSUE THREAD

**Issue by sanzoghenzo** [stephen-bunn/file-config#43]
### Expected Behavior

It would be wonderful if I can pass a path to load_json and dump_json methods, and they take care of checking/opening the file before reading/writing to it.

### Current Behavior

As of now, I have to pass a file object to these methods.

I need to manually add two new methods (let's call them save and load) to take the path string, open a file for reading/writing and then call load_json or dump_json.

**Comment by stephen-bunn** [comment]
The goal of this project is keeping the `dump` / `load` standard methods as just accepting file objects. Dealing with writing to file paths is commonly very open to interpretation, and for the purposes of this package, not in scope for the problem I'm intending to provide a solution for.

Some common issues when trying to interpret file paths for a module are the following:

- How to handle relative file paths?
- How to handle various OS specific file definitions (`file:///` as an example)
- What OS mode to open the file in, and what happens if you want to write to fake files?
- What to do if file system permissions doesn't allow writing to the parent directory?
- What to do in the case where the specified parent directory doesn't exist? (in most cases raise a `NotADirectoryError`)


IMO, the task of opening a file for writing is not up to the module, but whatever program is utilizing the module. This is partly the reason the default implementations of `json` and `yaml` don't provide functionality for interpreting file paths. So I'll leave this functionality up to the implementation and try and stick with the Python standards for serializing to file objects.

Thanks for the kind suggestion!

**Comment by sanzoghenzo** [comment]
Got it, thanks for taking care of studying the issue an reporting back!
